exec-once = lxpolkit &
exec-once = dunst &
exec-once = wl-clip-persist --clipboard regular &
exec-once = browser-daemon

exec-once = gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg
exec-once = swaybg -i ~/.background/background.jpg -m fill
