windowrule = suppress_event maximize, match:class .*
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false

windowrule = float on, match:class ^(launcher|calculator|system-monitor|anki|xdg-desktop-portal-gtk)$
windowrule = center on, match:class ^(launcher|calculator|anki|xdg-desktop-portal-gtk)$

windowrule = size 600 400, match:class ^(launcher|calculator)$
windowrule = size 700 600, match:class ^anki$
windowrule = size 600 500, match:class ^xdg-desktop-portal-gtk$

windowrule = move 10 62, match:class ^system-monitor$
windowrule = size 1900 1008, match:class ^system-monitor$

layerrule = blur on, match:namespace waybar
