windowrule = suppress_event maximize, match:class .*
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false

windowrule = float on, match:class ^(launcher|qalc|btop|anki|swayimg|xdg-desktop-portal-gtk)$
windowrule = center on, match:class ^(launcher|qalc|anki|swayimg|xdg-desktop-portal-gtk)$

windowrule = size 600 400, match:class ^qalc$
windowrule = size 700 500, match:class ^launcher$
windowrule = size 700 600, match:class ^(anki|xdg-desktop-portal-gtk)$
windowrule = size 800 600, match:class ^swayimg$

windowrule = move 10 62, match:class ^btop$
windowrule = size 1900 1008, match:class ^btop$

layerrule = blur on, match:namespace waybar
