$launcher = kitty-open launcher true
$qalc = kitty-open qalc true
$btop = kitty-open btop

$anki = fish -c "app anki"
$discord = fish -c "app discord"
$zen_browser = fish -c "app zen-browser"
$terminal = fish -c "app kitty"

$mainMod = SUPER
