$launcher = kitty-open launcher true
$calculator = kitty-open calculator true
$monitor = kitty-open monitor

$anki = fish -c anki
$discord = fish -c discord
$browser = fish -c browser
$terminal = fish -c kitty
$obsidian = fish -c obsidian

$mainMod = SUPER
