$btop = kitty-open btop
$qalc = kitty-open qalc true
$launcher = kitty-open launcher true

$anki = fish -c "app anki"
$thunar = fish -c "app thunar"
$terminal = fish -c "app kitty"
$discord = fish -c "app discord"
$zen_browser = fish -c "app zen-browser"

$mainMod = SUPER
