#!/bin/bash

wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-

volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
vol_percent=$(echo "$volume" | awk '{print int($2 * 100)}')

notify-send -a "[Audio]" -r 2 -t 1000 -h int:value:"$vol_percent" -h string:fgcolor:"#f8a83e" "$vol_percent% (-5%)"
