return {
  "nvim-treesitter/nvim-treesitter",
  lazy = false,
  build = ":TSUpdate",
  config = function()
    require("nvim-treesitter").install({
      "bash",
      "c",
      "cmake",
      "cpp",
      "css",
      "csv",
      "dockerfile",
      "gitignore",
      "html",
      "ini",
      "java",
      "javascript",
      "json",
      "rust",
      "toml",
      "lua",
      "make",
      "markdown",
      "markdown_inline",
      "nginx",
      "prisma",
      "python",
      "tsx",
      "typescript",
      "udev",
    })
  end,
}
